import tokens from "../../design-tokens/json/styles.json";

export const colors = {
  "$color-primary-1": tokens.ColorPrimary1,
  "$color-primary-2": tokens.ColorPrimary2,
  "$color-transparent-1": tokens.ColorTransparent1,
  "$color-transparent-2": tokens.ColorTransparent2,
  "$color-transparent-3": tokens.ColorTransparent3,
  "$color-transparent-4": tokens.ColorTransparent4,
  "$color-disable": tokens.ColorDisable,
  "$color-details": tokens.ColorDetails,
  "$color-success": tokens.ColorSuccess,
  "$color-info": tokens.ColorInfo,
  "$color-warning": tokens.ColorWarning,
  "$color-error": tokens.ColorError,
  "$color-calendar": tokens.ColorCalendar,
  "$color-black": tokens.ColorBlack,
  "$color-white": tokens.ColorBlack,
  "$color-secondary-1": tokens.ColorSecondary1,
  "$color-secondary-2": tokens.ColorSecondary2,
  "$color-secondary-3": tokens.ColorSecondary3,
  "$color-secondary-4": tokens.ColorSecondary4,
  "$color-secondary-5": tokens.ColorSecondary5,
  "$color-secondary-6": tokens.ColorSecondary6,
  "$color-tertiary-1": tokens.ColorTertiary1,
  "$color-tertiary-2": tokens.ColorTertiary2,
  "$color-tertiary-3": tokens.ColorTertiary3,
  "$color-tertiary-4": tokens.ColorTertiary4,
  "$color-tertiary-5": tokens.ColorTertiary5,
  "$color-tertiary-6": tokens.ColorTertiary6,
  "$color-neutral-1": tokens.ColorNeutral1,
  "$color-neutral-2": tokens.ColorNeutral2,
  "$color-neutral-3": tokens.ColorNeutral3,
  "$color-neutral-4": tokens.ColorNeutral4,
  "$color-neutral-5": tokens.ColorNeutral5,
  "$color-neutral-6": tokens.ColorNeutral6,
  "$color-neutral-7": tokens.ColorNeutral7,
  "$color-neutral-8": tokens.ColorNeutral8,
  "$color-neutral-9": tokens.ColorNeutral9,
  "$color-success-1": tokens.ColorSuccess1,
  "$color-success-2": tokens.ColorSuccess2,
  "$color-success-3": tokens.ColorSuccess3,
  "$color-success-4": tokens.ColorSuccess4,
  "$color-success-5": tokens.ColorSuccess5,
  "$color-success-6": tokens.ColorSuccess6,
  "$color-warning-1": tokens.ColorWarning1,
  "$color-warning-2": tokens.ColorWarning2,
  "$color-warning-3": tokens.ColorWarning3,
  "$color-warning-4": tokens.ColorWarning4,
  "$color-warning-5": tokens.ColorWarning5,
  "$color-warning-6": tokens.ColorWarning6,
  "$color-danger-1": tokens.ColorDanger1,
  "$color-danger-2": tokens.ColorDanger2,
  "$color-danger-3": tokens.ColorDanger3,
  "$color-danger-4": tokens.ColorDanger4,
  "$color-danger-5": tokens.ColorDanger5,
  "$color-danger-6": tokens.ColorDanger6,
  blackAlpha2: "#00000005",
  blackAlpha6: "#0000000F",
  blackAlpha15: "#00000026",
  blackAlpha25: "#00000040",
  blackAlpha45: "#00000073",
  blackAlpha85: "#000000d9",
  cyan5: "#36CFC9",
  cyan7: "#08979C",
  yellow1: "#FAAD14",
  white: "#FFFFFF",
  transparent: "transparent",
  gray: "#8C8C8C",
  icons: "#09121F",
  polarGreen6: "#52C41A",
  magenta6: "#EB2F96",
  neutralGray: "#FAFAFA",
  "$color-transparent-dark-10": tokens.ColorTransparentDark10,
  "$color-transparent-dark-25": tokens.ColorTransparentDark25,
  "$color-transparent-dark-40": tokens.ColorTransparentDark40,
  "$color-transparent-dark-65": tokens.ColorTransparentDark65,
  "$color-transparent-dark-75": tokens.ColorTransparentDark75,
  "$color-transparent-dark-95": tokens.ColorTransparentDark95,
  "$color-transparent-light-10": tokens.ColorTransparentLight10,
  "$color-transparent-light-25": tokens.ColorTransparentLight25,
  "$color-transparent-light-40": tokens.ColorTransparentLight40,
  "$color-transparent-light-65": tokens.ColorTransparentLight65,
  "$color-transparent-light-75": tokens.ColorTransparentLight75,
  "$color-transparent-light-95": tokens.ColorTransparentLight95,
};

export const text = {
  fonts: {
    ralewayRegular: "Raleway Regular, sans-serif",
    ralewayMedium: "Raleway Medium, sans-serif",
    ralewaySemiBold: "Raleway Semi-Bold, sans-serif",
    mavenProRegular: "Maven Pro Regular, sans-serif",
    mavenProMedium: "Maven Pro Medium, sans-serif",
    mavenProSemiBold: "Maven Pro SemiBold, sans-serif",
    mavenProBold: "Maven Pro Bold, sans-serif",
    mavenProExtraBold: "Maven Pro ExtraBold, sans-serif",
    mavenProBlack: "Maven Pro Black, sans-serif",
  },
  display: {
    xl: tokens.DesktopFontDisplayRegularXl,
    l: tokens.DesktopFontDisplayRegularL,
    m: tokens.DesktopFontDisplayRegularM,
    s: tokens.DesktopFontDisplayRegularS,
    xs: tokens.DesktopFontDisplayRegularXs,
  },
  displayBold: {
    xl: tokens.DesktopFontDisplayBoldXl,
    l: tokens.DesktopFontDisplayBoldL,
    m: tokens.DesktopFontDisplayBoldM,
    s: tokens.DesktopFontDisplayBoldS,
    xs: tokens.DesktopFontDisplayBoldXs,
  },
  body: {
    xl: tokens.DesktopFontBodyRegularXl,
    l: tokens.DesktopFontBodyRegularL,
    m: tokens.DesktopFontBodyRegularM,
    s: tokens.DesktopFontBodyRegularS,
  },
  bodyBold: {
    xl: tokens.DesktopFontBodyBoldXl,
    l: tokens.DesktopFontBodyBoldL,
    m: tokens.DesktopFontBodyBoldM,
    s: tokens.DesktopFontBodyBoldS,
  },
  opacity: {
    primary: "0.85",
    secondary: "0.45",
    disabled: "0.25",
  },
};

const sizing = {
  button: {
    large: "360px",
  },
  input: {
    large: "360px",
  },
  sidebar: "208px",
};

export const spacing = {
  cornerRadiusSmall: "4px",
};

export const shadows = {
  elevationLow: "0px 1px 0px rgba(240,240,240,1)",
  elevationMedium: "0px 3px 8px rgba(0, 0, 0, 0.12)",
  elevationHigh: "0px 7px 16px rgba(0, 0, 0, 0.12)",
};

const mainTheme = {
  colors,
  text,
  sizing,
  spacing,
  shadows,
};

export default mainTheme;
